version: "3.9"

services:
  pwn:
    build:
      context: .
      args:
        UID: $UID
        GID: $GID
        USERNAME: $USERNAME
        GROUPNAME: $GROUPNAME
    user: $UID:$GID
    tty: true
    cap_add:
      - "SYS_PTRACE"
    security_opt:
      - "seccomp=unconfined"
    # ports:
    # - "127.0.0.1:2222:2222"
    volumes:
      - /home/ryohz/ctf/imaginary2024/onewrite:/root/workspace:rw
